export const PRODUCT_LABELS = {
  code: "Kode Produk",
  name: "Nama Produk",
  slug: "Slug SEO",
  description: "Deskripsi",
  color: "Warna",
  badge: "Marketing Badge",
  productCategory: "Kategori",
  unit: "Satuan",
  sellingPrice: "Harga Jual",
  finalPrice: "Harga Setelah Diskon",
  purchasePrice: "Harga Beli",
  weightGram: "Berat (gram)",
  isActive: "Status Aktif",
  createdAt: "Dibuat",
} as const;
