export const STOCK_LABELS = {
  pageTitle: "Stok Varian",
  pageDescription: "Pantau dan catat perubahan stok pada level varian produk.",
  productCode: "Kode Produk",
  productName: "Produk",
  sku: "SKU",
  variantName: "Varian",
  stockOnHand: "Stok Saat Ini",
  isActive: "Status",
  movementType: "Tipe Mutasi",
  quantity: "Jumlah",
  balanceBefore: "Stok Sebelum",
  balanceAfter: "Stok Setelah",
  referenceType: "Referensi",
  referenceId: "ID Referensi",
  reason: "Alasan",
  note: "Catatan",
  createdAt: "Waktu",
  actions: "Aksi",
  addMovement: "Tambah Mutasi",
  movementHistory: "Riwayat Mutasi",
  selectVariant: "Pilih varian untuk melihat riwayat mutasi.",
} as const;
