export const INDONESIA_DATA: Record<string, string[]> = {
  "Aceh": [
    "Banda Aceh",
    "Sabang",
    "Lhokseumawe",
    "Langsa",
    "Subulussalam",
    "Aceh Besar",
    "Aceh Jaya",
    "Aceh Barat",
    "Aceh Barat Daya",
    "Aceh Selatan",
    "Aceh Singkil",
    "Aceh Tenggara",
    "Gayo Lues",
    "Aceh Tengah",
    "Bener Meriah",
    "Pidie",
    "Pidie Jaya",
    "Bireuen",
    "Aceh Utara",
    "Aceh Timur",
    "Aceh Tamiang",
    "Simeulue"
  ],
  "Bali": [
    "Denpasar",
    "Badung",
    "Gianyar",
    "Buleleng",
    "Tabanan",
    "Karangasem",
    "Klungkung",
    "Bangli",
    "Jembrana"
  ],
  "Banten": [
    "Tangerang",
    "Tangerang Selatan",
    "Serang",
    "Cilegon",
    "Pandeglang",
    "Lebak",
    "Tangerang Kabupaten",
    "Serang Kabupaten"
  ],
  "Bengkulu": [
    "Bengkulu",
    "Bengkulu Utara",
    "Bengkulu Selatan",
    "Rejang Lebong",
    "Lebong",
    "Kepahiang",
    "Muko Muko",
    "Seluma",
    "Kaur",
    "Bengkulu Tengah"
  ],
  "DI Yogyakarta": [
    "Yogyakarta",
    "Sleman",
    "Bantul",
    "Gunungkidul",
    "Kulon Progo"
  ],
  "DKI Jakarta": [
    "Jakarta Pusat",
    "Jakarta Barat",
    "Jakarta Utara",
    "Jakarta Timur",
    "Jakarta Selatan",
    "Kepulauan Seribu"
  ],
  "Gorontalo": [
    "Gorontalo",
    "Boalemo",
    "Bone Bolango",
    "Gorontalo Utara",
    "Pohuwato"
  ],
  "Jambi": [
    "Jambi",
    "Sungai Penuh",
    "Muaro Jambi",
    "Batanghari",
    "Bungo",
    "Tebo",
    "Merangin",
    "Sarolangun",
    "Tanjung Jabung Barat",
    "Tanjung Jabung Timur",
    "Kerinci"
  ],
  "Jawa Barat": [
    "Bandung",
    "Bekasi",
    "Depok",
    "Bogor",
    "Tasikmalaya",
    "Cimahi",
    "Sukabumi",
    "Cirebon",
    "Banjar",
    "Sumedang",
    "Garut",
    "Cianjur",
    "Karawang",
    "Purwakarta",
    "Subang",
    "Indramayu",
    "Majalengka",
    "Kuningan",
    "Ciamis",
    "Pangandaran",
    "Bandung Barat",
    "Bekasi Kabupaten",
    "Bogor Kabupaten",
    "Cirebon Kabupaten",
    "Sukabumi Kabupaten",
    "Tasikmalaya Kabupaten"
  ],
  "Jawa Tengah": [
    "Semarang",
    "Surakarta (Solo)",
    "Magelang",
    "Pekalongan",
    "Salatiga",
    "Tegal",
    "Banyumas (Purwokerto)",
    "Cilacap",
    "Kudus",
    "Jepara",
    "Klaten",
    "Brebes",
    "Boyolali",
    "Karanganyar",
    "Sragen",
    "Wonogiri",
    "Sukoharjo",
    "Temanggung",
    "Wonosobo",
    "Purworejo",
    "Kebumen",
    "Banjarnegara",
    "Purbalingga",
    "Pemalang",
    "Batang",
    "Kendal",
    "Demak",
    "Grobogan",
    "Blora",
    "Rembang",
    "Pati",
    "Semarang Kabupaten",
    "Pekalongan Kabupaten",
    "Tegal Kabupaten",
    "Magelang Kabupaten"
  ],
  "Jawa Timur": [
    "Surabaya",
    "Malang",
    "Kediri",
    "Probolinggo",
    "Pasuruan",
    "Madiun",
    "Batu",
    "Blitar",
    "Mojokerto",
    "Sidoarjo",
    "Gresik",
    "Banyuwangi",
    "Jember",
    "Bojonegoro",
    "Tuban",
    "Lamongan",
    "Ponorogo",
    "Pacitan",
    "Trenggalek",
    "Tulungagung",
    "Nganjuk",
    "Ngawi",
    "Magetan",
    "Jombang",
    "Lumajang",
    "Bondowoso",
    "Situbondo",
    "Bangkalan",
    "Sampang",
    "Pamekasan",
    "Sumenep",
    "Malang Kabupaten",
    "Kediri Kabupaten",
    "Probolinggo Kabupaten",
    "Pasuruan Kabupaten",
    "Madiun Kabupaten",
    "Blitar Kabupaten",
    "Mojokerto Kabupaten"
  ],
  "Kalimantan Barat": [
    "Pontianak",
    "Singkawang",
    "Kubu Raya",
    "Mempawah",
    "Sambas",
    "Sanggau",
    "Sintang",
    "Ketapang",
    "Melawi",
    "Sekadau",
    "Kayong Utara",
    "Landak",
    "Kapuas Hulu",
    "Bengkayang"
  ],
  "Kalimantan Selatan": [
    "Banjarmasin",
    "Banjarbaru",
    "Banjar",
    "Barito Kuala",
    "Tanah Laut",
    "Tanah Bumbu",
    "Kotabaru",
    "Tapin",
    "Hulu Sungai Selatan",
    "Hulu Sungai Tengah",
    "Hulu Sungai Utara",
    "Balangan",
    "Tabalong"
  ],
  "Kalimantan Tengah": [
    "Palangka Raya",
    "Kotawaringin Timur",
    "Kotawaringin Barat",
    "Kapuas",
    "Barito Selatan",
    "Barito Utara",
    "Barito Timur",
    "Murung Raya",
    "Katingan",
    "Seruyan",
    "Pulang Pisau",
    "Gunung Mas",
    "Lamandau",
    "Sukamara"
  ],
  "Kalimantan Timur": [
    "Samarinda",
    "Balikpapan",
    "Bontang",
    "Kutai Kartanegara",
    "Kutai Timur",
    "Kutai Barat",
    "Berau",
    "Paser",
    "Penajam Paser Utara",
    "Mahakam Ulu"
  ],
  "Kalimantan Utara": [
    "Tarakan",
    "Bulungan",
    "Malinau",
    "Nunukan",
    "Tana Tidung"
  ],
  "Kepulauan Bangka Belitung": [
    "Pangkalpinang",
    "Bangka",
    "Belitung",
    "Bangka Barat",
    "Bangka Tengah",
    "Bangka Selatan",
    "Belitung Timur"
  ],
  "Kepulauan Riau": [
    "Batam",
    "Tanjungpinang",
    "Bintan",
    "Karimun",
    "Natuna",
    "Kepulauan Anambas",
    "Lingga"
  ],
  "Lampung": [
    "Bandar Lampung",
    "Metro",
    "Lampung Selatan",
    "Lampung Tengah",
    "Lampung Utara",
    "Lampung Barat",
    "Lampung Timur",
    "Tanggamus",
    "Pringsewu",
    "Pesawaran",
    "Way Kanan",
    "Tulang Bawang",
    "Tulang Bawang Barat",
    "Mesuji",
    "Pesisir Barat"
  ],
  "Maluku": [
    "Ambon",
    "Tual",
    "Maluku Tengah",
    "Maluku Tenggara",
    "Kepulauan Tanimbar",
    "Buru",
    "Buru Selatan",
    "Seram Bagian Barat",
    "Seram Bagian Timur",
    "Kepulauan Aru",
    "Maluku Barat Daya"
  ],
  "Maluku Utara": [
    "Ternate",
    "Tidore Kepulauan",
    "Halmahera Utara",
    "Halmahera Barat",
    "Halmahera Selatan",
    "Halmahera Timur",
    "Halmahera Tengah",
    "Kepulauan Sula",
    "Pulau Morotai",
    "Pulau Taliabu"
  ],
  "Nusa Tenggara Barat": [
    "Mataram",
    "Bima",
    "Lombok Barat",
    "Lombok Tengah",
    "Lombok Timur",
    "Lombok Utara",
    "Sumbawa",
    "Sumbawa Barat",
    "Dompu"
  ],
  "Nusa Tenggara Timur": [
    "Kupang",
    "Ende",
    "Sikka",
    "Flores Timur",
    "Alor",
    "Belu",
    "Rote Ndao",
    "Manggarai",
    "Manggarai Barat",
    "Manggarai Timur",
    "Sumba Timur",
    "Sumba Barat",
    "Sumba Tengah",
    "Sumba Barat Daya",
    "Sabu Raijua",
    "Malaka",
    "Timor Tengah Utara",
    "Timor Tengah Selatan",
    "Nagekeo",
    "Ngada"
  ],
  "Papua": [
    "Jayapura",
    "Keerom",
    "Sarmi",
    "Mamberamo Raya",
    "Biak Numfor",
    "Supiori",
    "Kepulauan Yapen",
    "Waropen"
  ],
  "Papua Barat": [
    "Manokwari",
    "Fakfak",
    "Kaimana",
    "Teluk Wondama",
    "Teluk Bintuni",
    "Pegunungan Arfak",
    "Manokwari Selatan"
  ],
  "Papua Selatan": [
    "Merauke",
    "Boven Digoel",
    "Mappi",
    "Asmat"
  ],
  "Papua Tengah": [
    "Nabire",
    "Mimika",
    "Paniai",
    "Dogiyai",
    "Deiyai",
    "Intan Jaya",
    "Puncak",
    "Puncak Jaya"
  ],
  "Papua Pegunungan": [
    "Jayawijaya",
    "Lanny Jaya",
    "Tolikara",
    "Yahukimo",
    "Yalimo",
    "Mamberamo Tengah",
    "Nduga",
    "Pegunungan Bintang"
  ],
  "Papua Barat Daya": [
    "Sorong",
    "Raja Ampat",
    "Sorong Selatan",
    "Maybrat",
    "Tambrauw"
  ],
  "Riau": [
    "Pekanbaru",
    "Dumai",
    "Kampar",
    "Bengkalis",
    "Indragiri Hulu",
    "Indragiri Hilir",
    "Pelalawan",
    "Rokan Hulu",
    "Rokan Hilir",
    "Siak",
    "Kuantan Singingi",
    "Kepulauan Meranti"
  ],
  "Sulawesi Barat": [
    "Mamuju",
    "Majene",
    "Polewali Mandar",
    "Mamasa",
    "Pasangkayu",
    "Mamuju Tengah"
  ],
  "Sulawesi Selatan": [
    "Makassar",
    "Palopo",
    "Parepare",
    "Gowa",
    "Maros",
    "Pangkajene dan Kepulauan",
    "Barru",
    "Bone",
    "Soppeng",
    "Wajo",
    "Sidrap",
    "Pinrang",
    "Enrekang",
    "Luwu",
    "Luwu Utara",
    "Luwu Timur",
    "Tana Toraja",
    "Toraja Utara",
    "Takalar",
    "Jeneponto",
    "Bantaeng",
    "Bulukumba",
    "Kepulauan Selayar",
    "Sinjai"
  ],
  "Sulawesi Tengah": [
    "Palu",
    "Donggala",
    "Sigi",
    "Poso",
    "Tojo Una-Una",
    "Tolitoli",
    "Buol",
    "Parigi Moutong",
    "Banggai",
    "Banggai Kepulauan",
    "Banggai Laut",
    "Morowali",
    "Morowali Utara"
  ],
  "Sulawesi Tenggara": [
    "Kendari",
    "Baubau",
    "Kolaka",
    "Kolaka Utara",
    "Kolaka Timur",
    "Konawe",
    "Konawe Utara",
    "Konawe Selatan",
    "Konawe Kepulauan",
    "Muna",
    "Muna Barat",
    "Buton",
    "Buton Utara",
    "Buton Selatan",
    "Buton Tengah",
    "Wakatobi",
    "Bombana"
  ],
  "Sulawesi Utara": [
    "Manado",
    "Bitung",
    "Tomohon",
    "Kotamobagu",
    "Minahasa",
    "Minahasa Utara",
    "Minahasa Selatan",
    "Minahasa Tenggara",
    "Bolaang Mongondow",
    "Bolaang Mongondow Utara",
    "Bolaang Mongondow Selatan",
    "Bolaang Mongondow Timur",
    "Kepulauan Sangihe",
    "Kepulauan Talaud",
    "Kepulauan Sitaro"
  ],
  "Sumatera Barat": [
    "Padang",
    "Bukittinggi",
    "Payakumbuh",
    "Solok",
    "Sawahlunto",
    "Padang Panjang",
    "Pariaman",
    "Pesisir Selatan",
    "Solok Selatan",
    "Sijunjung",
    "Dharmasraya",
    "Tanah Datar",
    "Padang Pariaman",
    "Agam",
    "Lima Puluh Kota",
    "Pasaman",
    "Pasaman Barat",
    "Kepulauan Mentawai"
  ],
  "Sumatera Selatan": [
    "Palembang",
    "Lubuklinggau",
    "Pagar Alam",
    "Prabumulih",
    "Ogan Komering Ulu",
    "Ogan Komering Ilir",
    "Muara Enim",
    "Lahat",
    "Musi Rawas",
    "Musi Banyuasin",
    "Banyuasin",
    "Ogan Ilir",
    "Empat Lawang",
    "Ogan Komering Ulu Timur",
    "Ogan Komering Ulu Selatan",
    "Penukal Abab Lematang Ilir",
    "Musi Rawas Utara"
  ],
  "Sumatera Utara": [
    "Medan",
    "Binjai",
    "Tebing Tinggi",
    "Pematangsiantar",
    "Tanjungbalai",
    "Sibolga",
    "Padangsidimpuan",
    "Gunungsitoli",
    "Deli Serdang",
    "Langkat",
    "Karo",
    "Simalungun",
    "Asahan",
    "Labuhanbatu",
    "Tapanuli Utara",
    "Tapanuli Tengah",
    "Tapanuli Selatan",
    "Nias",
    "Mandailing Natal",
    "Toba",
    "Dairi",
    "Samosir",
    "Humbang Hasundutan",
    "Pakpak Bharat",
    "Serdang Bedagai",
    "Batubara",
    "Padang Lawas",
    "Padang Lawas Utara",
    "Labuhanbatu Selatan",
    "Labuhanbatu Utara",
    "Nias Utara",
    "Nias Barat",
    "Nias Selatan"
  ]
};

export const PROVINCE_MAPPING: Record<string, string> = {
  "JKT": "DKI Jakarta",
  "JB": "Jawa Barat",
  "BT": "Banten"
};

export function normalizeProvince(val: string): string {
  return PROVINCE_MAPPING[val] || val;
}
